### ISSUE TITLE
Truth中存在一些错误

### ISSUE THREAD

**Issue by YuxiBupt** [destwang/DCN#5]
您好，感谢您公开了代码，我按照您的流程跑了一下，只是batch_size设置不同，到那时结果大概低一个百分点；另外分析sighan15的测试集结果，发现Truth数据集中有一些错误，比如： (pid=A2-1311-2)	这女人告所他的大学在那里。 这里预测出来告诉，但是truth中实际上是没有这个错误的，所以数据集是没有经过清洗是吗？

**Comment by destwang** [comment]
你好，SIGHAN15测试集标注本身存在一些问题，不是所有的错误都被标注出来了。为了和其他工作进行公平对比，我们没有对标注错误进行额外处理。

**Comment by YuxiBupt** [comment]
好的，谢谢您的回复



在 2021-09-27 09:18:32，"Baoxin Wang" ***@***.***> 写道：

你好，SIGHAN15测试集标注本身存在一些问题，不是所有的错误都被标注出来了。为了和其他工作进行公平对比，我们没有对标注错误进行额外处理。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
