### ISSUE TITLE
How to download the datasets?

### ISSUE THREAD

**Issue by Huren900** [destwang/DCN#6]
The dataset link need username and code, but i only see the code.
Can you provide the username to download the train set?
Thank you.

**Comment by Yang-HangWA** [comment]
@destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 
![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)

**Comment by destwang** [comment]
> @destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 ![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)

我让非讯飞的朋友试了一下，是可以正常下载的。确认一下访问地址是否正确？
http://pan.iflytek.com/#/link/4D6FBE3B7CCCD160E5041BD9B37D4252
密码：tmjX

**Comment by Yang-HangWA** [comment]
@destwang  很尴尬，一样的，不知道在遇到截图界面如何操作。。。需要输入域账号。。

**Comment by Yang-HangWA** [comment]
@destwang 通过别人帮助已经拿到了数据。。

**Comment by ThuJiang** [comment]
> > @destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 ![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)
> 
> 我让非讯飞的朋友试了一下，是可以正常下载的。确认一下访问地址是否正确？ http://pan.iflytek.com/#/link/4D6FBE3B7CCCD160E5041BD9B37D4252 密码：tmjX

您好，请问这个下载链接的数据就是论文里预训练用的Chinese Wikipedia texts吗？但是只有281831条，论文里说的是7756725条。

**Comment by destwang** [comment]
> > > @destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 ![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)
> > 
> > 
> > 我让非讯飞的朋友试了一下，是可以正常下载的。确认一下访问地址是否正确？ http://pan.iflytek.com/#/link/4D6FBE3B7CCCD160E5041BD9B37D4252 密码：tmjX
> 
> 您好，请问这个下载链接的数据就是论文里预训练用的Chinese Wikipedia texts吗？但是只有281831条，论文里说的是7756725条。

里面不包含维基百科预训练数据，我最近会整理下预训练部分代码和数据，预计两周内放出。

**Comment by ThuJiang** [comment]
> > > > @destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 ![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)
> > > 
> > > 
> > > 我让非讯飞的朋友试了一下，是可以正常下载的。确认一下访问地址是否正确？ http://pan.iflytek.com/#/link/4D6FBE3B7CCCD160E5041BD9B37D4252 密码：tmjX
> > 
> > 
> > 您好，请问这个下载链接的数据就是论文里预训练用的Chinese Wikipedia texts吗？但是只有281831条，论文里说的是7756725条。
> 
> 里面不包含维基百科预训练数据，我最近会整理下预训练部分代码和数据，预计两周g

> > > > @destwang 数据共享平台是科大讯飞内部的，我们没办法登录，输入你们写的tmjX依然需要登录。 ![1639364656(1)](https://user-images.githubusercontent.com/38546249/145745981-a13c776e-48fc-4fcb-82d6-35c440100fc3.png)
> > > 
> > > 
> > > 我让非讯飞的朋友试了一下，是可以正常下载的。确认一下访问地址是否正确？ http://pan.iflytek.com/#/link/4D6FBE3B7CCCD160E5041BD9B37D4252 密码：tmjX
> > 
> > 
> > 您好，请问这个下载链接的数据就是论文里预训练用的Chinese Wikipedia texts吗？但是只有281831条，论文里说的是7756725条。
> 
> 里面不包含维基百科预训练数据，我最近会整理下预训练部分代码和数据，预计两周内放出。

感谢！
